var semana1 = 
		[
			[
				document.getElementsByClassName("e_1"),
				document.getElementsByClassName("e_3"),
				document.getElementsByClassName("e_5")
			],
			[
				document.getElementsByClassName("e_2"),
				document.getElementsByClassName("e_4"),
				document.getElementsByClassName("e_6")
			]
		],
	semana2 = 
		[
			[
				document.getElementsByClassName("e_8"),
				document.getElementsByClassName("e_10"),
				document.getElementsByClassName("e_12")
			],
			[
				document.getElementsByClassName("e_9"),
				document.getElementsByClassName("e_11"),
				document.getElementsByClassName("e_13")
			]
		],
	semana3 = 
		[
			[
				document.getElementsByClassName("e_15"),
				document.getElementsByClassName("e_17"),
				document.getElementsByClassName("e_19")
			],
			[
				document.getElementsByClassName("e_16"),
				document.getElementsByClassName("e_18"),
				document.getElementsByClassName("e_20")
			]
		],
	semana4 = 
		[
			[
				document.getElementsByClassName("e_22"),
				document.getElementsByClassName("e_24"),
				document.getElementsByClassName("e_26")
			],
			[
				document.getElementsByClassName("e_23"),
				document.getElementsByClassName("e_25"),
				document.getElementsByClassName("e_27")
			]
		],
	semana5 = 
		[
			[
				document.getElementsByClassName("e_29"),
				document.getElementsByClassName("e_31"),
				document.getElementsByClassName("e_33")
			],
			[
				document.getElementsByClassName("e_30"),
				document.getElementsByClassName("e_32"),
				document.getElementsByClassName("e_34")
			]
		],
	semana6 = 
		[
			[
				document.getElementsByClassName("f_e_29"),
				document.getElementsByClassName("f_e_31"),
				document.getElementsByClassName("f_2")
			],
			[
				document.getElementsByClassName("f_e_30"),
				document.getElementsByClassName("f_1"),
				document.getElementsByClassName("f_3")
			]
		],
	semana7=
		[
			[
				document.getElementsByClassName("f_5"),
				document.getElementsByClassName("f_7"),
				document.getElementsByClassName("f_9")
			],
			[
				document.getElementsByClassName("f_6"),
				document.getElementsByClassName("f_8"),
				document.getElementsByClassName("f_10")
			]
		]
	semana8 = 
		[
			[
				document.getElementsByClassName("f_12"),
				document.getElementsByClassName("f_14"),
				document.getElementsByClassName("f_16")
			],
			[
				document.getElementsByClassName("f_13"),
				document.getElementsByClassName("f_15"),
				document.getElementsByClassName("f_17")
			]
		],
	semana9 = 
		[
			[
				document.getElementsByClassName("f_19"),
				document.getElementsByClassName("f_21"),
				document.getElementsByClassName("f_23")
			],
			[
				document.getElementsByClassName("f_20"),
				document.getElementsByClassName("f_22"),
				document.getElementsByClassName("f_24")
			]
		],
	semana10 = 
		[
			[
				document.getElementsByClassName("f_26"),
				document.getElementsByClassName("f_28"),
				document.getElementsByClassName("f_m_2")
			],
			[
				document.getElementsByClassName("f_27"),
				document.getElementsByClassName("f_m_1"),
				document.getElementsByClassName("f_m_3")
			]
		],
	semana11 = 
		[
			[
				document.getElementsByClassName("m_f_26"),
				document.getElementsByClassName("m_f_28"),
				document.getElementsByClassName("m_2")
			],
			[
				document.getElementsByClassName("m_f_27"),
				document.getElementsByClassName("m_1"),
				document.getElementsByClassName("m_3")
			]
		],
	semana12 = 
		[
			[
				document.getElementsByClassName("m_5"),
				document.getElementsByClassName("m_7"),
				document.getElementsByClassName("m_9")
			],
			[
				document.getElementsByClassName("m_6"),
				document.getElementsByClassName("m_8"),
				document.getElementsByClassName("m_10")
			]
		],
	semana13 = 
		[
			[
				document.getElementsByClassName("m_12"),
				document.getElementsByClassName("m_14"),
				document.getElementsByClassName("m_16")
			],
			[
				document.getElementsByClassName("m_13"),
				document.getElementsByClassName("m_15"),
				document.getElementsByClassName("m_17")
			]
		],
	semana14 = 
		[
			[
				document.getElementsByClassName("m_19"),
				document.getElementsByClassName("m_21"),
				document.getElementsByClassName("m_23")
			],
			[
				document.getElementsByClassName("m_20"),
				document.getElementsByClassName("m_22"),
				document.getElementsByClassName("m_24")
			]
		],
	semana15 = 
		[
			[
				document.getElementsByClassName("m_26"),
				document.getElementsByClassName("m_28"),
				document.getElementsByClassName("m_30")
			],
			[
				document.getElementsByClassName("m_27"),
				document.getElementsByClassName("m_29"),
				document.getElementsByClassName("m_31")
			]
		]
		;
	var listaDeHermanos = 	[semana1,
						semana2,
						semana3,
						semana4,
						semana5,
						semana6,
						semana7,
						semana8,
						semana9,
						semana10,
						semana11,
						semana12,
						semana13];
function derA(){
	reseteaTodo();
	document.getElementById("contieneCalendario").classList.add("derechaMoverA");
}
function derB(){
	reseteaTodo();
	document.getElementById("contieneCalendario").classList.add("derechaMoverB");
}
function izqA(){
	reseteaTodo();
	document.getElementById("contieneCalendario").classList.add("izquierdaMoverA");
}
function izqB(){
	reseteaTodo();
	document.getElementById("contieneCalendario").classList.add("izquierdaMoverB");
}
function reseteaTodo(){
	document.getElementById("contieneCalendario").classList.remove("derechaMoverA");
	document.getElementById("contieneCalendario").classList.remove("derechaMoverB");
	document.getElementById("contieneCalendario").classList.remove("izquierdaMoverA");
	document.getElementById("contieneCalendario").classList.remove("izquierdaMoverB");
}